blank_issues_enabled: false
contact_links:
  - name: Get support
    url: https://github.com/CoC-MS/security-template/blob/main/SUPPORT.md
    about: Use SUPPORT.md for usage questions, implementation guidance, and general assistance.
